# Generated by Django 6.0.3 on 2026-03-14 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('address', models.TextField(default='Not provided')),
                ('department', models.CharField(max_length=100)),
                ('status', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
