# Generated by Django 6.0.3 on 2026-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('qualification', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('BSc', 'BSc')], max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('BBA', 'BBA')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admission',
                'db_table': 'admission',
                'ordering': ['-created_at'],
            },
        ),
    ]
